branches:
  only:
    - dev
    - master
language: node_js
node_js:
  - "7"
  - "8"
os:
  - linux
install:
  - yarn
script:
  - yarn lint
  - yarn dev-build
deploy:
  provider: surge
  project: ./demo-dist/
  domain: https://nuxt7.surge.sh